### ISSUE TITLE
tbh your wrap per sucks (tbh your gram mar sucks)

### ISSUE THREAD

**Issue by fourjr** [SharpBit/abrawlpy#1]
1. loop and session should be grabbed as a kwarg in Client init 👍 
2. `__str__` should be a method for player and band, etc 👍 
3. `self.timeout = options.get('timeout')` should have a default of `5` 👍 
4. Tags should be pre-checked instead of polling the API and getting an invalid tag 👍 
5. `from .errors import *` should not be a wildcard import 👍 
6. more of a personal preference, all errors should include **endpoint** that includes **tag** 👍 
7. 
```py
band = Band(raw_data, camel_killer_box=True)
return band
```
what's the use of creating a var here 👍 
8. why specify `camel_killer_box=True)` all the time? why not just create  a box base class for your wrapper where you specify that in the init? 👍 
9. `get_player ` should be alias for ` get_profile` 👍 
10. ```timeout: Optional[int]
Quits requests to the API 
``` should be `**timeout ` in docstrings 👍 
11. get the request code for unauthorized `401`? 🤔 
~~think~~ hope that's it
12. in `__init__.py`: 
```py
from .core import *
from .errors import *
from .utils import API
```
import utils isn't needed here? 👍 
13. send only one message in the dpy cog example (readme.md) 👍 
14. in all docstrings, for kwargs use `**varname ` instead of `varname ` 👍 
15. `Get your token by DMing Zihad#6591 on Discord or ask in the API Server.` update plox 👍

**Comment by fourjr** [comment]
forgot this:
`except abrawlpy.errors.RequestError as e: ` according to your init.py, `except abrawlpy.RequestError` should be good enough

**Comment by SharpBit** [comment]
1. Wildcard error import? Wdym by this, cuz all errors were used in the file
2.  for `__str__` I just inherit it from box class
3. "All errors should include **endpoint** that includes **tag**: ???
4. By prechecked do you mean: upper case, replace O with 0, and make sure only tag characters are used?

**Comment by fourjr** [comment]
1. it's never good to have a wildcard import, as stated in pep8
2. have a str for player like: `4JR (#2P0LYQ) `
3. Errors are vague, and not good for production, it should at least include the endpoint which was requested 
4. yes.

**Comment by SharpBit** [comment]
Why does the endpoint matter? Doesn't the error state where it was (such as get_band)

**Comment by fourjr** [comment]
it's easier to debug when you have the tag used that caused the error

**Comment by SharpBit** [comment]
Does pep8 really matter when it's less characters and words? :/

**Comment by fourjr** [comment]
pep8 always matters ;)   
but it's much clearer as to what's imported and where stuff are defined

**Comment by SharpBit** [comment]
fixed everything in here and your commit comments, if you find more issues, open another issue
